[versions]
whistle = "dev-SNAPSHOT"

[libraries]
google-whistle-core-runtime = { module = "com.essaid.groupId.com.google.cloud.verticals.foundations.dataharmonization:runtime", version.ref = "whistle" }